yaml
title: "TASK L3C"
email: "carl@tokyotaskforce.com"
description: "Building disaster readiness in Japan before the next disaster"
baseurl: "/task-website-rebuild"
url: "https://taskl3c.github.io"
github_username: taskl3c

# Serif theme settings
header_pages:
  - index.md
  - vision.md
  - programs.md
  - transparency.md
  - contact.md

# Build settings
theme: jekyll-serif-theme
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Custom variables
mission_statement: "Japan shouldn't face the next disaster unprepared"
